networks:
  app-network:
    driver: bridge
  mon-network:
    driver: bridge

volumes:
  db_data_opencart-3:
  db_data_victoriametrics:

include:
  - ./prod/docker-app-compose.yml
  - ./prod/docker-mon-compose.yml
