networks:
  cms-network:
    driver: bridge
  mon-network:
    driver: bridge

volumes:
  db_data_opencart-3:
  db_data_victoriametrics:
  db_data_grafana:

include:
  - ./prod/docker-cms-compose.yml
  - ./prod/docker-mon-compose.yml
