global:
  resolve_timeout: 1m
  http_config:
    follow_redirects: true
    enable_http2: true
  smtp_hello: localhost
  smtp_require_tls: true
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  opsgenie_api_url: https://api.opsgenie.com/
  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
  telegram_api_url: https://api.telegram.org
  webex_api_url: https://webexapis.com/v1/messages

route:
  receiver: telegram.channel.warning
  group_by: [alertname]
  continue: false
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  routes:
    - receiver: 'telegram.channel.critical'
      match:
        severity: critical
    - receiver: 'telegram.channel.warning'
      match:
        severity: warning

inhibit_rules:
  - source_match:
      severity: 'critical'
      alertname: PrometheusConfigurationReload
    target_match:
      severity: 'error'

receivers:
  - name: telegram.channel.critical
    telegram_configs:
      - bot_token: 7249040814:AAG903y3N0SQFa2r_KtslPUL6sQPtXyFQnE
        api_url: https://api.telegram.org
        chat_id: -1002209045779
        parse_mode: ''
  - name: telegram.channel.warning
    telegram_configs:
      - bot_token: 7249040814:AAG903y3N0SQFa2r_KtslPUL6sQPtXyFQnE
        api_url: https://api.telegram.org
        chat_id: -1002195446054
        parse_mode: ''

templates: []
