global:
  # How frequently to scrape targets
  scrape_interval:     1m
  # How frequently to evaluate rules
  evaluation_interval: 30s
  # Add label to each sample before sending it to remote storage
  external_labels:
    site: prod

# Send data to VictoriaMetrics
remote_write:
  - url: http://victoria-metrics:8428/api/v1/write

# Rules and alerts are read from the specified file(s)
rule_files:
  - rules.yml

# Alerting specifies settings related to the Alertmanager
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - prometheus-alertmanager:9093

# A list of scrape configurations that specifies a set of
# targets and parameters describing how to scrape them.
scrape_configs:
  - job_name: 'prometheus_server'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus-server:9090']
    relabel_configs:
      - target_label: instance
        replacement: mon_prometheus-server

  - job_name: 'node_exporter'
    scheme: https
    basic_auth:
      username: prom_mon_user
      password: prom_mon_user
    tls_config:
      insecure_skip_verify: true
    metrics_path: /node-exporter/
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus-proxy']
    relabel_configs:
      - target_label: instance
        replacement: cms_node

  - job_name: 'nginx_exporter'
    scheme: https
    basic_auth:
      username: prom_mon_user
      password: prom_mon_user
    tls_config:
      insecure_skip_verify: true
    metrics_path: /nginx-exporter/
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus-proxy']
        labels:
          scrape_uri: 'http://frontend:8008/stub_status'
    relabel_configs:
      - target_label: instance
        replacement: cms_frontend

  - job_name: 'php-fpm_exporter'
    scheme: https
    basic_auth:
      username: prom_mon_user
      password: prom_mon_user
    tls_config:
      insecure_skip_verify: true
    metrics_path: /php-fpm-exporter/
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus-proxy']
    relabel_configs:
      - target_label: instance
        replacement: cms_php-fpm

  - job_name: 'mysqld_exporter'
    scheme: https
    basic_auth:
      username: prom_mon_user
      password: prom_mon_user
    tls_config:
      insecure_skip_verify: true
    metrics_path: /mysqld-exporter
    scrape_interval: 5s
    static_configs:
      - targets:
          - database:3306
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: instance
        replacement: cms_database
      - target_label: __address__
        replacement: prometheus-proxy

  - job_name: 'blackbox_exporter'
    scheme: https
    basic_auth:
      username: prom_mon_user
      password: prom_mon_user
    tls_config:
      insecure_skip_verify: true
    metrics_path: /blackbox-exporter
    params:
      module: [http_2xx]
    scrape_interval: 5s
    static_configs:
      - targets: [https://frontend]
        labels:
          scrape_uri: 'https://frontend'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: instance
        replacement: cms_frontend
      - target_label: __address__
        replacement: prometheus-proxy
