{
 "title": "App сumulative dashboard",
 "tags": [
  "cms",
  "app"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "App instances status",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "nginx_up{instance=\"cms_frontend\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "phpfpm_up{pool=\"www\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "mysql_up{instance=\"cms_database\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Frontend latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_http_duration_seconds{instance=\"cms_frontend\",job=\"blackbox_exporter\"}",
     "legendFormat": "{{phase}} {{scrape_uri}}"
    }
   ]
  },
  {
   "title": "PHP-FPM latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "round(avg by (child,pool) (phpfpm_process_request_duration))",
     "legendFormat": "{{child}}:{{pool}}"
    }
   ]
  },
  {
   "title": "Database connections errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_connection_errors_total{instance=\"cms_database\"}[1m])",
     "legendFormat": "{{instance}}: {{error}}"
    }
   ]
  }
 ]
}